# Generated by Django 5.0.2 on 2024-10-26 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=200)),
                ('todo_desc', models.TextField()),
                ('time_created', models.DateTimeField(default=datetime.datetime(2024, 10, 26, 6, 5, 52, 290663))),
                ('todo_status', models.BooleanField(default=False)),
            ],
        ),
    ]
