# Generated by Django 5.0.2 on 2024-10-26 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 6, 50, 21, 601660)),
        ),
    ]
