# Generated by Django 5.0.2 on 2024-10-26 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 6, 53, 18, 382342)),
        ),
    ]
