# Generated by Django 5.0.2 on 2024-10-26 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_category',
            field=models.CharField(choices=[('Work', 'Work'), ('Chores', 'Chores'), ('Leisures', 'Leisuire'), ('Travel', 'Travel'), ('None', 'None')], default='None', max_length=8),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 18, 2, 33, 894677)),
        ),
    ]
